# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Votem Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Votem Example
  pod 'JVFloatLabeledTextField', '~> 1.2'
  pod 'AFNetworking', '~> 3.1'
  pod 'Masonry', '~> 1.0'
  pod 'Mantle', '~> 2.1'
  pod 'SAMKeychain', '~> 1.5'
  pod 'IQKeyboardManager' 

  target 'Votem ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  post_install do |installer|
    require 'fileutils'
    FileUtils.cp_r('Pods/Target Support Files/Pods-Votem Example/Pods-Votem Example-acknowledgements.plist', 'Votem Example/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
  end
end
